#!/bin/bash
set -e
source /usr/share/debconf/confmodule
db_version 2.0

db_get ipfs-kubo/system-wide || true
IPFS_SYSTEMWIDE="${RET}"
db_get ipfs-kubo/user-name || true
IPFS_USERNAME="${RET}"

if [[ "${1}" == "remove" || "${1}" == "purge" ]]
then
    if [[ "${IPFS_SYSTEMWIDE}" == "true" ]]
    then
        if [[ -f /etc/profile.d/ipfs.sh ]]
        then
            rm /etc/profile.d/ipfs.sh
        fi
    else
        USER_PROFILE_SCRIPT="$(getent passwd ${IPFS_USERNAME} | cut -d: -f6)/.profile"
        sed -i -e '/^.*export\ *IPFS\_PATH=/d' ${USER_PROFILE_SCRIPT}
    fi
fi

if [[ "${1}" == "purge" && "${IPFS_SYSTEMWIDE}" == "true" ]]
then
    deb-systemd-helper purge ipfs.service
    db_input critical ipfs-kubo/repository-purge || true
    db_input critical ipfs-kubo/config-purge || true
    db_go || true
    db_get ipfs-kubo/repository-purge || true
    if [[ "${RET}" == "true" ]]
    then
        db_get ipfs-kubo/repository-directory || true
        rm -rf "${RET}"
    fi
    db_get ipfs-kubo/config-purge || true
    if [[ "${RET}" == "true" ]]
    then
        db_get ipfs-kubo/predefined-config || true
        rm -f "${RET}"
    fi
    if getent group "ipfs" &>/dev/null 
    then
        delgroup --system --only-if-empty "ipfs"
    fi
    db_purge || true
else
    deb-systemd-helper disable ipfs.service
fi

#DEBHELPER#

