#!/bin/bash

TAG_STRING=""
VERSION_STRING=""
MD_CHANGELOG_FILE=""
TEMPLOG=$(mktemp)
CHANGELOG_FILE="${1}"
TIMESTAMP=$(date +"%a, %d %b %Y %H:%M:%S %z")

if git describe --tags --exact-match > /dev/null 2>&1
then
    TAG_STRING=$(git describe --tags --exact-match)
    VERSION_STRING=$(echo -e "${TAG_STRING}" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
    if [[ -z "${VERSION_STRING}" ]]
    then
        echo 'ERROR! Version string parser error'
        exit 1
    fi
    MD_CHANGELOG_FILE="./docs/changelogs/$(echo -e "${TAG_STRING}" | grep -o -E 'v[0-9]+\.[0-9]+').md"
    if [[ ! -f "${MD_CHANGELOG_FILE}" ]]
    then
        echo -e "ERROR! Changelog file ${CWD}/${MD_CHANGELOG_FILE} does not exist!"
        exit 1
    fi
    tee "${TEMPLOG}" > /dev/null << EOM
ipfs-kubo (${VERSION_STRING}) UNRELEASED; urgency=low

  [ IPFS Development Team and Contributors ]
EOM
    awk '/<details>/,/<\/details>/' "${MD_CHANGELOG_FILE}" | sed -n '/<details>/,/<\/details>/p' | sed 's/<details>//;s/<\/details>//' | sed '/<summary>/d' | sed '/^$/d' | sed -e 's/^-\ \+/\ \ \*\ /;s/^\ \+-\ \+/\ \ \ \ /' | sed -E 's/\(*\[(.*)\]\((.*)\)/ \2\1/g' | fmt -w 80 -s | tee --append "${TEMPLOG}" > /dev/null
    tee --append "${TEMPLOG}" > /dev/null << EOM
  * Full changelog
    https://github.com/twdragon/kubo/blob/master/docs/changelogs/$(echo -e "${TAG_STRING}" | grep -o -E 'v[0-9]+\.[0-9]+').md

 -- IPFS Community & Contributors <info@ipfs.tech>  ${TIMESTAMP}

EOM
    if [[ -f "${CHANGELOG_FILE}" ]]
    then
        cat "${CHANGELOG_FILE}" >> "${TEMPLOG}"
        DUPLICATES=$(grep -o -E '^ipfs-kubo\ *\([0-9]+\.[0-9]+\.[0-9]+\)' "${TEMPLOG}" | sort | uniq -d)
        if [[ ! -z "${DUPLICATES}" ]]
        then
            echo 'ERROR! Version strings duplication detected! Please check the tag name you have checked out, and verify if you really need to update the Debian changelog.'
            exit 1
        fi
    fi
    cat ${TEMPLOG} > "${CHANGELOG_FILE}"
else
    echo 'WARNING! The repository is not checked on the tag. The changelog file will not be generated!'
fi

trap 'rm -vf "${TEMPLOG}"' EXIT

