#!/bin/bash
set -e
source /usr/share/debconf/confmodule
db_version 2.0

db_get ipfs-kubo/system-wide || true
IPFS_SYSTEMWIDE="${RET}"

if [[ "${1}" == "purge" && "${IPFS_SYSTEMWIDE}" == "true" ]]
then
    deb-systemd-helper purge ipfs.service
    db_input critical ipfs-kubo/repository-purge || true
    db_input critical ipfs-kubo/config-purge || true
    db_go || true
    db_get ipfs-kubo/repository-purge || true
    if [[ "${RET}" == "true" ]]
    then
        db_get ipfs-kubo/repository-directory || true
        rm -rf "${RET}"
    fi
    db_get ipfs-kubo/config-purge || true
    if [[ "${RET}" == "true" ]]
    then
        db_get ipfs-kubo/predefined-config || true
        rm -f "${RET}"
    fi
    db_get ipfs-kubo/user-name
    if id "${RET}" &>/dev/null
    then
        deluser --system --remove-home "${RET}"
    fi
    if getent group "ipfs" &>/dev/null 
    then
        delgroup --system --only-if-empty "ipfs"
    fi
    db_purge || true
else
    deb-systemd-helper disable ipfs.service
fi

