#!/bin/sh
set -e
source /usr/share/debconf/confmodule
db_version 2.0

if [[ systemctl list-unit-files | grep -q "^ipfs" ]]
then
    if [[ systemctl is-active --quiet "ipfs" ]]
    then
        systemctl stop "ipfs"
    fi
fi

db_get ipfs-kubo/repository-directory || true
IPFS_REPOSITORY="${RET}"
db_get ipfs-kubo/predefined-config || true
IPFS_CONFIG="${RET}"
cp "${IPFS_REPOSITORY}/config" "${IPFS_CONFIG}"
