#!/bin/bash

TAG_STRING=""
VERSION_STRING=""
TEMPLOG=$(mktemp)
CHANGELOG_FILE="${1}"
TIMESTAMP=$(date +"%a, %d %b %Y %H:%M:%S %z")
DISTRO_CODENAME="UNRELEASED"

if [[ ! -z "${2}" ]]
then
    DISTRO_CODENAME="${2}"
fi

if git describe --tags --exact-match > /dev/null 2>&1
then
    TAG_STRING=$(git describe --tags --exact-match)
    VERSION_STRING=$(echo -e "${TAG_STRING}" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
    if [[ -z "${VERSION_STRING}" ]]
    then
        echo 'ERROR! Version string parser error'
        exit 1
    fi
    LAST_MESSAGES=$(git log ${TAG_STRING} --pretty=format:"  * %s")
    tee "${TEMPLOG}" > /dev/null << EOM
libp2p-relay (${VERSION_STRING}) ${DISTRO_CODENAME}; urgency=low

  [ libp2p Development Team and Contributors ]
EOM
    echo "${LAST_MESSAGES}" | sed '/^$/d' | sed -e 's/^-\ \+/\ \ \*\ /;s/^\ \+-\ \+/\ \ \ \ /' | sed -E 's/\(*\[(.*)\]\((.*)\)./ \2\ \1/g' | fmt -w 80 -s | tee --append "${TEMPLOG}" > /dev/null
    tee --append "${TEMPLOG}" > /dev/null << EOM

 -- Protocol Labs <contact@protocol.ai>  ${TIMESTAMP}

EOM
    cat ${TEMPLOG} > "${CHANGELOG_FILE}"
else
    TAG_STRING=$(git describe --tags --abbrev=0)
    COMMIT_LAST=$(git rev-parse --short HEAD)
    CLEAR_VERSION_STRING=$(echo -e "${TAG_STRING}" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
    VERSION_STRING="${CLEAR_VERSION_STRING}+git${COMMIT_LAST}"
    LAST_MESSAGES=$(git log ${TAG_STRING}..HEAD --pretty=format:"  * %s")
    tee "${TEMPLOG}" > /dev/null << EOM
libp2p-relay (${VERSION_STRING}) ${DISTRO_CODENAME}; urgency=low

  [ libp2p Development Team and Contributors ]
EOM
    echo "${LAST_MESSAGES}" | sed '/^$/d' | sed -e 's/^-\ \+/\ \ \*\ /;s/^\ \+-\ \+/\ \ \ \ /' | sed -E 's/\(*\[(.*)\]\((.*)\)./ \2\ \1/g' | fmt -w 80 -s | tee --append "${TEMPLOG}" > /dev/null
    tee --append "${TEMPLOG}" > /dev/null << EOM
  * END OF UNRELEASED CHANGES - Nightly build. Please use at your own risk!
EOM
    tee --append "${TEMPLOG}" > /dev/null << EOM

 -- Protocol Labs <contact@protocol.ai>  ${TIMESTAMP}

EOM
    PREV_TAG=$(git describe --tags --abbrev=0 "${TAG_STRING}^")
    LAST_MESSAGES=$(git log ${PREV_TAG}..${TAG_STRING} --pretty=format:"  * %s")
    tee --append "${TEMPLOG}" > /dev/null << EOM
libp2p-relay (${CLEAR_VERSION_STRING}) ${DISTRO_CODENAME}; urgency=low

  [ libp2p Development Team and Contributors ]
EOM
    echo "${LAST_MESSAGES}" | sed '/^$/d' | sed -e 's/^-\ \+/\ \ \*\ /;s/^\ \+-\ \+/\ \ \ \ /' | sed -E 's/\(*\[(.*)\]\((.*)\)./ \2\ \1/g' | fmt -w 80 -s | tee --append "${TEMPLOG}" > /dev/null
    TAG_CREATED=$(git log -1 --format=%ct "${TAG_STRING}")
    TAG_TIMESTAMP=$(date -d "@${TAG_CREATED}" +"%a, %d %b %Y %H:%M:%S %z")
    tee --append "${TEMPLOG}" > /dev/null << EOM

 -- Protocol Labs <contact@protocol.ai>  ${TAG_TIMESTAMP}

EOM
    cat ${TEMPLOG} > "${CHANGELOG_FILE}"
fi

LAST_TAG=$(git describe --tags --abbrev=0)
RETROSPECTIVE_TAGS=$(git for-each-ref --sort=-creatordate --format='%(refname:short)' refs/tags | grep -A 1000000 "${LAST_TAG}" | grep -v "${LAST_TAG}")
for GIT_TAG in $RETROSPECTIVE_TAGS
do
    TAG_CREATED=$(git log -1 --format=%ct "${GIT_TAG}")
    TAG_TIMESTAMP=$(date -d "@${TAG_CREATED}" +"%a, %d %b %Y %H:%M:%S %z")
        VERSION_STRING=$(echo -e "${GIT_TAG}" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
        PREV_TAG=$(git describe --tags --always --abbrev=0 "${GIT_TAG}^")
        LAST_MESSAGES=$(git log ${PREV_TAG}..${GIT_TAG} --pretty=format:"  * %s")
        tee --append "${TEMPLOG}" > /dev/null << EOM
libp2p-relay (${VERSION_STRING}) ${DISTRO_CODENAME}; urgency=low

  [ libp2p Development Team and Contributors ]
EOM
        echo "${LAST_MESSAGES}" | sed '/^$/d' | sed -e 's/^-\ \+/\ \ \*\ /;s/^\ \+-\ \+/\ \ \ \ /' | sed -E 's/\(*\[(.*)\]\((.*)\)./ \2\ \1/g' | fmt -w 80 -s | tee --append "${TEMPLOG}" > /dev/null
        tee --append "${TEMPLOG}" > /dev/null << EOM

 -- Protocol Labs <contact@protocol.ai>  ${TAG_TIMESTAMP}

EOM
        cat ${TEMPLOG} > "${CHANGELOG_FILE}"
done

trap 'rm -vf "${TEMPLOG}"' EXIT

