#!/bin/bash
set -e
source /usr/share/debconf/confmodule
db_version 2.0

if [[ "${1}" == "purge" ]]
then
    if [[ -f "/etc/libp2p/id" ]]
    then
        rm -f "/etc/libp2p/id"
    fi
    deb-systemd-helper purge libp2p-relay.service
    db_purge || true
else
    deb-systemd-helper disable libp2p-relay.service
fi

#DEBHELPER#

